"""add sources table

Revision ID: fabf95fa275c
Revises: 802cbaee49d0
Create Date: 2026-09-06 18:01:57.697623

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fabf95fa275c"
down_revision: str | Sequence[str] | None = "802cbaee49d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sources = op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.bulk_insert(sources, [{"slug": "remotive", "enabled": True}])

    op.create_foreign_key(None, "raw_postings", "sources", ["source_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "raw_postings", type_="foreignkey")
    op.drop_table("sources")
    # ### end Alembic commands ###
